import React, { useState, useEffect } from 'react';
import { Quiz, Question, Subject } from '../types';
import { getStoredQuizzes, saveQuiz, saveNotification } from '../lib/dbStore';
import { Search, Trash2, HelpCircle, GraduationCap, BookOpen, Tag, ChevronDown, ChevronUp, SlidersHorizontal, AlertCircle, FileText, Check, Sparkles, Play } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface QuestionsInventoryProps {
  userRole: 'teacher' | 'admin';
  onEnterTest?: (quizId: string) => void;
}

interface InventoryItem {
  quizId: string;
  quizTitle: string;
  subject: Subject;
  classLevel: 11 | 12;
  question: Question;
}

export default function QuestionsInventory({ userRole, onEnterTest }: QuestionsInventoryProps) {
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSubject, setSelectedSubject] = useState<'All' | Subject>('All');
  const [selectedClass, setSelectedClass] = useState<'All' | '11' | '12'>('All');
  const [selectedDifficulty, setSelectedDifficulty] = useState<'All' | 'Easy' | 'Medium' | 'Hard'>('All');
  const [sortBy, setSortBy] = useState<'syllabus' | 'recent' | 'difficulty'>('recent');
  const [expandedQuestionId, setExpandedQuestionId] = useState<string | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState('');

  // Load all questions from database quizzes
  const loadInventory = () => {
    const quizzes = getStoredQuizzes();
    const allItems: InventoryItem[] = [];

    quizzes.forEach((quiz) => {
      if (quiz.questions && Array.isArray(quiz.questions)) {
        quiz.questions.forEach((q) => {
          allItems.push({
            quizId: quiz.id,
            quizTitle: quiz.title,
            subject: quiz.subject,
            classLevel: quiz.classLevel,
            question: q,
          });
        });
      }
    });

    setItems(allItems);
  };

  useEffect(() => {
    loadInventory();
    window.addEventListener('db-quizzes-updated', loadInventory);
    return () => {
      window.removeEventListener('db-quizzes-updated', loadInventory);
    };
  }, []);

  const handleToggleExpand = (id: string) => {
    setExpandedQuestionId(expandedQuestionId === id ? null : id);
  };

  const handleDeleteQuestion = (quizId: string, questionId: string) => {
    const quizzes = getStoredQuizzes();
    const targetQuiz = quizzes.find((q) => q.id === quizId);

    if (targetQuiz) {
      const originalCount = targetQuiz.questions.length;
      targetQuiz.questions = targetQuiz.questions.filter((q) => q.id !== questionId);
      saveQuiz(targetQuiz);

      setSuccessMsg('Question deleted successfully from the test series.');
      setDeleteConfirmId(null);

      // Save admin/teacher notification alert
      saveNotification({
        id: `q-removed-${Date.now()}`,
        title: '🗑️ Question Deleted from Quiz',
        message: `A question was deleted from "${targetQuiz.title}" by a faculty member.`,
        type: 'exam_alert',
        timestamp: new Date().toISOString(),
        read: false,
      });

      setTimeout(() => setSuccessMsg(''), 4000);
    }
  };

  // Helper to extract timestamp from question ID if it was added manually or generated by AI
  const getQuestionTimestamp = (qId: string): number => {
    const parts = qId.split('-');
    for (let p of parts) {
      const num = Number(p);
      if (!isNaN(num)) {
        if (num > 1500000000000) { // millisecond timestamp (e.g. Date.now())
          return num;
        } else if (num > 1500000000) { // second timestamp
          return num * 1000;
        }
      }
    }
    return 1; // Default low so they sort below user/faculty additions
  };

  // Filter items
  const filteredItems = items.filter((item) => {
    const matchesSearch =
      item.question.text.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.question.topic.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.quizTitle.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (item.question.explanation && item.question.explanation.toLowerCase().includes(searchTerm.toLowerCase()));

    const matchesSubject = selectedSubject === 'All' || item.subject === selectedSubject;
    const matchesClass = selectedClass === 'All' || item.classLevel.toString() === selectedClass;
    const matchesDifficulty = selectedDifficulty === 'All' || item.question.difficulty === selectedDifficulty;

    return matchesSearch && matchesSubject && matchesClass && matchesDifficulty;
  });

  // Dynamic sort
  const sortedAndFilteredItems = [...filteredItems].sort((a, b) => {
    if (sortBy === 'recent') {
      const timeA = getQuestionTimestamp(a.question.id);
      const timeB = getQuestionTimestamp(b.question.id);
      if (timeA !== timeB) {
        return timeB - timeA; // newer questions on top
      }
      return b.question.id.localeCompare(a.question.id);
    } else if (sortBy === 'difficulty') {
      const diffWeight: Record<string, number> = { 'Easy': 1, 'Medium': 2, 'Hard': 3 };
      return (diffWeight[b.question.difficulty] || 0) - (diffWeight[a.question.difficulty] || 0); // Harder first
    } else {
      // standard syllabus index: Class, then Subject, then Quiz Title
      if (a.classLevel !== b.classLevel) {
        return a.classLevel - b.classLevel;
      }
      if (a.subject !== b.subject) {
        return a.subject.localeCompare(b.subject);
      }
      return a.quizTitle.localeCompare(b.quizTitle);
    }
  });

  return (
    <div id="questions-inventory" className="bg-white border border-slate-200 rounded-[2.25rem] p-6 sm:p-8 shadow-sm space-y-6 font-sans">
      
      {/* Header section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-100">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-xl">
            <BookOpen className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-lg font-black tracking-tight text-slate-900 font-display">Questions Core Inventory</h3>
            <p className="text-xs text-slate-500 mt-1">Review, search, inspect solutions, and manage all questions deployed across chapters.</p>
          </div>
        </div>
        <div className="text-xs font-bold text-slate-500 bg-slate-50 px-3.5 py-2 border border-slate-200/60 rounded-xl font-mono text-center md:text-left self-start md:self-auto">
          Total Inventory: <span className="text-indigo-600 font-black">{items.length} questions</span>
        </div>
      </div>

      {successMsg && (
        <div className="p-4 bg-emerald-50 text-emerald-850 border border-emerald-200 rounded-2xl text-xs font-bold flex items-center gap-2 animate-fade-in">
          <Check className="h-4 w-4 text-emerald-600" />
          {successMsg}
        </div>
      )}

      {/* Search & Filter bar combo */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-3">
        {/* Search Input */}
        <div className="lg:col-span-5 relative">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search questions keyword, topic, chapter proof..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-50 text-xs text-slate-700 border border-slate-200 pl-10 pr-4 py-3 rounded-xl focus:outline-none focus:border-indigo-500 focus:bg-white font-medium"
          />
        </div>

        {/* Filters Group */}
        <div className="lg:col-span-7 grid grid-cols-4 gap-2 text-xs">
          {/* Subject Filter */}
          <div className="flex flex-col gap-0.5">
            <select
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 px-3 py-3 rounded-xl font-bold cursor-pointer text-slate-705"
            >
              <option value="All">All Subjects</option>
              <option value="Physics">Physics</option>
              <option value="Chemistry">Chemistry</option>
              <option value="Mathematics">Mathematics</option>
            </select>
          </div>

          {/* Class Filter */}
          <div className="flex flex-col gap-0.5">
            <select
              value={selectedClass}
              onChange={(e) => setSelectedClass(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 px-3 py-3 rounded-xl font-bold cursor-pointer text-slate-705"
            >
              <option value="All">All Classes</option>
              <option value="11">Class 11</option>
              <option value="12">Class 12</option>
            </select>
          </div>

          {/* Difficulty Filter */}
          <div className="flex flex-col gap-0.5">
            <select
              value={selectedDifficulty}
              onChange={(e) => setSelectedDifficulty(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 px-3 py-3 rounded-xl font-bold cursor-pointer text-slate-705"
            >
              <option value="All">All Difficulty</option>
              <option value="Easy">Easy</option>
              <option value="Medium">Medium</option>
              <option value="Hard">Hard</option>
            </select>
          </div>

          {/* Sorting Command Selector */}
          <div className="flex flex-col gap-0.5">
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as any)}
              className="w-full bg-indigo-50/55 border border-indigo-200/60 text-indigo-700 px-3 py-3 rounded-xl font-extrabold cursor-pointer text-slate-705"
            >
              <option value="recent">⏱️ Newest First</option>
              <option value="syllabus">📚 Syllabus Chapters</option>
              <option value="difficulty">🔥 Hardest First</option>
            </select>
          </div>
        </div>
      </div>

      {/* Questions list container */}
      <div className="space-y-3.5">
        {sortedAndFilteredItems.length === 0 ? (
          <div className="text-center py-12 border border-dashed border-slate-200 bg-slate-50/50 rounded-2-xl">
            <SlidersHorizontal className="h-8 w-8 text-slate-400 mx-auto stroke-[1.25] mb-2" />
            <h4 className="text-xs font-bold text-slate-700">No matching questions found</h4>
            <p className="text-[11px] text-slate-400 mt-0.5">Try clearing filters or search parameters.</p>
          </div>
        ) : (
          sortedAndFilteredItems.map((item) => {
            const isExpanded = expandedQuestionId === item.question.id;
            const isDeleting = deleteConfirmId === item.question.id;
            const difficulty = item.question.difficulty;

            return (
              <div
                key={item.question.id}
                className={`border rounded-2xl transition-all overflow-hidden ${
                  isExpanded ? 'bg-indigo-50/10 border-indigo-200 shadow-sm' : 'bg-white border-slate-200/80 hover:border-slate-300'
                }`}
              >
                {/* Question Row Header */}
                <div
                  onClick={() => handleToggleExpand(item.question.id)}
                  className="p-4 sm:p-5 flex items-start gap-3 cursor-pointer select-none"
                >
                  <div className="flex-grow space-y-1.5 min-w-0">
                    <div className="flex flex-wrap items-center gap-2 text-[10px]">
                      <span className={`px-2 py-0.5 rounded-md font-black uppercase text-[9px] ${
                        item.subject === 'Physics' ? 'bg-blue-50 text-blue-700 border border-blue-100' :
                        item.subject === 'Chemistry' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' :
                        'bg-purple-50 text-purple-700 border border-purple-100'
                      }`}>
                        {item.subject} CL-{item.classLevel}
                      </span>
                      <span className="text-slate-400">•</span>
                      <span className="text-slate-500 font-semibold truncate max-w-xs">{item.quizTitle}</span>
                      <span className="text-slate-400">•</span>
                      <span className="text-slate-400 font-mono font-bold">{item.question.topic}</span>
                    </div>

                    <h4 className="text-xs font-bold text-slate-800 leading-relaxed pr-6">
                      {item.question.text}
                    </h4>
                  </div>

                  <div className="flex items-center gap-3 shrink-0 self-center">
                    {/* Difficulty Badge */}
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                      difficulty === 'Easy' ? 'bg-green-50 text-green-700 border border-green-200' :
                      difficulty === 'Medium' ? 'bg-amber-50 text-amber-700 border border-amber-200' :
                      'bg-rose-50 text-rose-700 border border-rose-200'
                    }`}>
                      {difficulty}
                    </span>

                    {isExpanded ? (
                      <ChevronUp className="h-4 w-4 text-slate-400" />
                    ) : (
                      <ChevronDown className="h-4 w-4 text-slate-400" />
                    )}
                  </div>
                </div>

                {/* Question Details Expander */}
                <AnimatePresence initial={false}>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.15 }}
                      className="border-t border-slate-100 bg-slate-50/50"
                    >
                      <div className="p-4 sm:p-5 space-y-5 text-xs">
                        {/* Options breakdown */}
                        <div className="space-y-2">
                          <h5 className="font-black text-slate-400 text-[10px] uppercase tracking-wider font-mono">Multiple Choice Options</h5>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                            {item.question.options.map((opt, oIdx) => {
                              const isCorrect = oIdx === item.question.correctAnswerIndex;
                              return (
                                <div
                                  key={oIdx}
                                  className={`p-3 rounded-xl border flex items-start gap-2.5 transition-all ${
                                    isCorrect
                                      ? 'bg-emerald-50 border-emerald-200 text-emerald-800 font-bold'
                                      : 'bg-white border-slate-200 text-slate-700'
                                  }`}
                                >
                                  <span className={`w-5 h-5 rounded-full shrink-0 text-[11px] font-black flex items-center justify-center ${
                                    isCorrect ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-500'
                                  }`}>
                                    {String.fromCharCode(65 + oIdx)}
                                  </span>
                                  <span className="leading-snug">{opt}</span>
                                </div>
                              );
                            })}
                          </div>
                        </div>

                        {/* Visual Image Support if present */}
                        {item.question.imageUrl && (
                          <div className="p-1 border border-slate-200 rounded-xl bg-white max-w-md">
                            <img src={item.question.imageUrl} alt="Syllabus visual guide" className="rounded-lg object-contain max-h-56 w-full" referrerPolicy="no-referrer" />
                          </div>
                        )}

                        {/* Solution explanation */}
                        <div className="bg-white p-4 border border-slate-200/70 rounded-2xl space-y-1.5">
                          <div className="flex items-center gap-1.5 text-indigo-600 font-bold text-[10px] uppercase font-mono">
                            <HelpCircle className="h-4 w-4 text-indigo-500" />
                            Solution & Scientific Reasoning
                          </div>
                          <p className="text-slate-600 leading-relaxed font-medium pl-5.5">
                            {item.question.explanation}
                          </p>
                        </div>

                        {/* Delete action panel */}
                        <div className="flex justify-between items-center pt-3 border-t border-slate-100">
                          <span className="text-[10px] text-slate-400 font-mono">
                            ID: <span className="font-semibold">{item.question.id}</span>
                          </span>

                          <div className="flex items-center gap-2">
                            {isDeleting ? (
                              <div className="flex items-center gap-1.5 bg-red-50 border border-red-200 px-3 py-1.5 rounded-xl text-[10px] text-red-700 font-bold animate-pulse-short">
                                <span>Delete this question permanently?</span>
                                <button
                                  onClick={() => handleDeleteQuestion(item.quizId, item.question.id)}
                                  className="px-2 py-1 bg-rose-600 hover:bg-rose-700 text-white rounded-lg font-black"
                                >
                                  Confirm
                                </button>
                                  <button
                                    onClick={() => setDeleteConfirmId(null)}
                                    className="px-2 py-1 bg-white border border-slate-300 text-slate-600 rounded-lg hover:bg-slate-50"
                                  >
                                    Cancel
                                  </button>
                              </div>
                            ) : (
                              <div className="flex items-center gap-1.5">
                                {onEnterTest && (
                                  <button
                                    onClick={() => onEnterTest(item.quizId)}
                                    className="flex items-center gap-1.5 text-rose-600 hover:text-rose-700 font-extrabold px-3 py-2 rounded-xl hover:bg-rose-50/50 transition-all text-[11px] cursor-pointer"
                                    title="Try this entire exam in Faculty Demo Mode"
                                  >
                                    <Sparkles className="h-3.5 w-3.5 fill-current text-rose-500 animate-pulse" />
                                    <span>Try Demo Exam</span>
                                  </button>
                                )}
                                 <button
                                   onClick={() => setDeleteConfirmId(item.question.id)}
                                   className="flex items-center gap-1.5 text-red-600 hover:text-red-700 font-extrabold px-3 py-2 rounded-xl hover:bg-red-50 transition-all text-[11px] cursor-pointer"
                                 >
                                   <Trash2 className="h-3.5 w-3.5" />
                                   Remove Question
                                 </button>
                              </div>
                            )}
                          </div>
                        </div>

                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })
        )}
      </div>

    </div>
  );
}
